# yaml-language-server: $schema=vendor/phpro/grumphp-shim/grumphp.phar/vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
    php:
        container_name: ticket-flow-api.php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/app
        environment:
            APP_ENV: ${APP_ENV:-dev}
            SERVER_NAME: ${SERVER_NAME:-localhost}
            XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST:-}
        ports:
            - "8080:80"
            - "8443:443"
            - "8443:443/udp"
        networks:
            - local
        extra_hosts:
            - "host.docker.internal:host-gateway"

    postgres:
        image: postgres:18.4-alpine
        container_name: ticket-flow-api.postgres
        restart: no
        ports:
            - '${DATABASE_PORT:-5432}:5432'
        environment:
            POSTGRES_USER: '${DATABASE_USER}'
            POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
            POSTGRES_DB: '${DATABASE_DB}'
        volumes:
            - pgdata:/var/lib/postgresql:rw
        networks:
            - local

volumes:
    pgdata:

networks:
    local: