services:
  php:
    container_name: ticket-flow-api.php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
    environment:
      APP_ENV: ${APP_ENV:-dev}
      SERVER_NAME: ${SERVER_NAME:-localhost}
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST:-}
    ports:
      - "8080:80"
      - "8443:443"
      - "8443:443/udp"
